### ISSUE TITLE
Similar projects

### ISSUE THREAD

**Issue by TechnologyClassroom** [zrafa/onscreenkeyboard#5]
Have you tried these?  Maybe you will find their project or code useful.

- key-mon
https://code.google.com/archive/p/key-mon/

- screenkey
https://github.com/wavexx/screenkey

- matchbox-keyboard
https://github.com/xlab/matchbox-keyboard

**Comment by craftyguy** [comment]
@TechnologyClassroom I don't think those are really similar to this project. They require things like python and X11, whereas this project just requires the linux kernel, a framebuffer device, and input device. This is typically all that is available during boot when running in initramfs. Adding any more would make initramfs too large for some embedded/mobile devices.
